### ISSUE TITLE
Rematch issue 

### ISSUE THREAD

**Issue by somenormalguy7** [IOKernel/chess-bot#1]
Whenever I press rematch chess bot won't work and in tournaments also chess bot won't work.

Can you fix these issues?

**Comment by IOKernel** [comment]
Changed the code so that you need to type 'start' after you start any new match, should work in tournament mode as well.
Will post a proper fix/rework later.

**Comment by somenormalguy7** [comment]
> Changed the code so that you need to type 'start' after you start any new match, should work in tournament mode as well.
> Will post a proper fix/rework later.

Thank you
