### ISSUE TITLE
Suggestion: Add this to Readme

### ISSUE THREAD

**Issue by SolsticeSpectrum** [IOKernel/chess-bot#14]
Chess.com actually has policy on engines. People can use your project freely as long as they play unrated and NOTIFY the opponent in chat.

Here is the statement from fair play rules
```EXCEPTION: These rules do not apply to unrated games or tactics. However, if you intend to use assistance against your opponent, you must notify them beforehand. We may expand or narrow any applicable exceptions to the Fair Play Policy at any time without notice to you.```

**Comment by IOKernel** [comment]
Added, thanks.
